name: Build Artifacts

on:
  push:
    branches:
      - '**'
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt

      - name: Run BuildTools
        run: . .github/scripts/buildtools.sh

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build Spigot-Mapped
        run: ./gradlew clean addonJar "-DoutDir=artifacts/"

      - name: Upload Artifacts
        id: upload
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: ./artifacts/*.jar

      - name: Publish Artifacts
        if: github.event_name == 'release'
        uses: skx/github-action-publish-binaries@release-2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ./artifacts/*.jar
