name: Build Artifacts

on:
  push:
    branches:
      - '**'
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-disabled: true

      - name: Build Spigot-Mapped
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            addonJar
            -PoutDir=artifacts
            -PxenondevsNms
            --scan
        env:
          ORG_GRADLE_PROJECT_xenondevsNmsUsername: ${{ secrets.XENONDEVS_NMS_USERNAME }}
          ORG_GRADLE_PROJECT_xenondevsNmsPassword: ${{ secrets.XENONDEVS_NMS_PASSWORD }}

      - name: Upload Artifacts
        id: upload
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: ./artifacts/*.jar

      - name: Attach Artifacts to Release
        if: github.event_name == 'release'
        uses: skx/github-action-publish-binaries@release-2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ./artifacts/*.jar